timeout: 600s
steps:
- id: cloudRunDeploy
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
    - -c
    - |
      gcloud builds submit --tag gcr.io/$PROJECT_ID/abtest-staged-demo:2 -q
      gcloud beta run deploy --image gcr.io/$PROJECT_ID/abtest-staged-demo:2 -q --allow-unauthenticated --platform="managed" --region="us-central1" abtest-staged-demo
